### ISSUE TITLE
typo on number tutorial

### ISSUE THREAD

**Issue by Just-some-one** [java/devjava-content#107]
on the first table of [the intro of the number tutorial](https://dev.java/learn/numbers-strings/numbers/#intro)

on the 4th row it mention that the toString() method  is static

> static toString()  Returns a String object representing the value of this Integer.

static should be removed

**Comment by JosePaumard** [comment]
Done. Thank you for your report.

**Comment by Just-some-one** [comment]
thanks for you @JosePaumard
