### ISSUE TITLE
multi wrong link and missing links of the Strings tutorial

### ISSUE THREAD

**Issue by Just-some-one** [java/devjava-content#110]
for the [String to numbers section](https://dev.java/learn/numbers-strings/strings/#strings-to-numbers)

second paragraph

> The Number subclasses that wrap primitive numeric types (Byte, Integer, Double, Float, Long, and Short each provide a class method named valueOf() that converts a string to an object of that type. Here is an example, ValueOfDemo, that gets two strings from the command line, converts them to numbers, and performs arithmetic operations on the values:

valueOf method link is for the one that accept int but it should be linked to the one that accept string
so the correct link is https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/lang/Integer.html#valueOf(java.lang.String)

same issue with the valueOf method here on the note after the result of the demo code

> Note: Each of the Number subclasses that wrap primitive numeric types also provides a parseXXXX() method. For example, parseFloat() can be used to convert strings to primitive numbers. Since a primitive type is returned instead of an object, the parseFloat() method is more direct than the valueOf() method. For example, in the ValueOfDemo program, we could use:

another issue with the link to the toString method on [the Converting Numbers to Strings section](https://dev.java/learn/numbers-strings/strings/#numbers-to-strings) 

> Each of the Number subclasses includes a class method, toString(), that will convert its primitive type to a string. For example:

the toString method link is for the toString on the number class which is not overridden there so it would be better to refer to one of the subclass of number like integer or no link at all not sure which it more suitable

for [Other Methods for Manipulating Strings](https://dev.java/learn/numbers-strings/strings/#manipulating) 

the first point mention the regular expression

> Regular expressions are covered in the section titled "Regular Expressions."

so it can be linked to the regex tutorial https://dev.java/learn/regex/

for [Comparing Strings and Portions of Strings section](https://dev.java/learn/numbers-strings/strings/#comparing) 

the link to regionMatches here

> boolean regionMatches(int toffset, String other, int ooffset, int len): Tests whether the specified region of this string matches the specified region of the String argument. Region is of length len and begins at the index toffset for this string and ooffset for the other string.

should be https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/lang/String.html#regionMatches(int,java.lang.String,int,int)

and for

> boolean matches(String regex): Tests whether this string matches the specified regular expression. Regular expressions are discussed in the lesson titled "Regular Expressions."

a link to the regex tutorial would be nice

and have a nice day :)

**Comment by JosePaumard** [comment]
Done. Thank you for your report!

**Comment by Just-some-one** [comment]
thanks for you @JosePaumard
