### ISSUE TITLE
[Request] add section for how char is represented and the supplementary and BMP for char

### ISSUE THREAD

**Issue by Just-some-one** [java/devjava-content#111]
adding section or tutorial for char representation in java

1. what the codepoint 
2. what is unicode
3. issue that could raise when deal with char from the supplementary plane 
4. how string length count char 
5. may be some hint for [the searching section of the String tutorial](https://dev.java/learn/numbers-strings/strings/#searching-chars-substrings) why the indexOf used int not char 

thanks and have a nice day :)

**Comment by danthe1st** [comment]
Codepoints and some things about unicode are explained in [this tutorial about characters](https://dev.java/learn/numbers-strings/characters/#code-points)
