### ISSUE TITLE
typo on links on StringBuilder and autoboxing tutorial

### ISSUE THREAD

**Issue by Just-some-one** [java/devjava-content#112]
for the [String builder tutorial](https://dev.java/learn/numbers-strings/string-builders/#length-capacity)

> StringBuilder(CharSequence cs): Constructs a string builder containing the same characters as the specified CharSequence, plus an extra 16 empty elements trailing the CharSequence. 

and 

> StringBuilder(String s): Creates a string builder whose value is initialized by the specified string, plus an extra 16 empty elements trailing the string.

both link to the constructor need to be corrected

for the javadoc 

those 2 line need to be updated

```
"StringBuilder(CharSequence)":            "java/lang/StringBuilder.html#%3Cinit%3E(java.lang.CharSequence)",
  "StringBuilder(String)":                  "java/lang/StringBuilder.html#%3Cinit%3E(java.lang.String)",
```

to be

```
"StringBuilder(CharSequence)":            "java.base/java/lang/StringBuilder.html#%3Cinit%3E(java.lang.CharSequence)",
  "StringBuilder(String)":                  "java.base/java/lang/StringBuilder.html#%3Cinit%3E(java.lang.String)",

```

to fix the issue 

for the [autoboxing tutorial](https://dev.java/learn/numbers-strings/autoboxing/) 

> The rest of the examples in this section use generics. If you are not yet familiar with the syntax of generics, see the Generics section.

a link to the generic tutorial would be nice
https://dev.java/learn/generics/

and have a nice day :)

**Comment by JosePaumard** [comment]
Done. Thank you!

**Comment by Just-some-one** [comment]
thanks for you @JosePaumard
