### ISSUE TITLE
exception and collections typo

### ISSUE THREAD

**Issue by Just-some-one** [java/devjava-content#115]
for [exception](https://dev.java/learn/exceptions/what-is-an-exception/)

The exception handler chosen is said to catch the exception. If the runtime system exhaustively searches all the methods on the call stack without finding an appropriate exception handler, as shown in the next figure, the runtime system (and, consequently, the program) terminates.

that depend if the exception happen on app with single thread or not

for [collection part](https://dev.java/learn/api/collections-framework/collection-interface/#adding-removing-elements)

> remove(element): removes the given element from the collection. This method also returns a boolean, because the operation may fail. A remove may fail, for instance, when the item requested for removal is not present in the collection

wrong link for the remove(element) method

> You can see removeAll() in action on the following example:

> You can see addAll() in action on the following example:

those 2 lines should be swapped

> The third one is removeAll(). It removes all the elements of this collection that are contained in the other collection. Just as it is the case for contains() or remove(), the other collection can be defined on any type; it does not have to be compatible with the one of this collection.

and

> The last one is retainAll(). This operation retains only the elements from this collection that are contained in the other collection; all the others are removed. Once again, as it is the case for contains() or remove(), the other collection can be defined on any type.

wrong link for the remove() method

for [choosing key](https://dev.java/learn/api/collections-framework/choosing-keys/)

> What will happen is someone mutates your key? Well, it really depends on the mutation. You can try the ones in the following example, and see what is happening when you try to get your values back. 

should be 

What will happen if someone mutates your key?

`if not is`

thanks for your time and have a nice day :)

**Comment by JosePaumard** [comment]
Done, thank you, and have a nice day yoo!

**Comment by Just-some-one** [comment]
thanks for you

for (adding removing)[https://dev.java/learn/api/collections-framework/collection-interface/#adding-removing-elements]

> remove(element: removes the given element from the collection. This method also returns a boolean, because the operation may fail. A remove may fail, for instance, when the item requested for removal is not present in the collection

the link should be https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/util/Collection.html#remove(java.lang.Object) 
it's not generic parameter it object


for (adding removing collections)[https://dev.java/learn/api/collections-framework/collection-interface/#adding-removing-collections]

first occurrence of 

> You can see removeAll() in action on the following example:

should be 

You can see addAll() in action on the following example:


>The last one is retainAll(). This operation retains only the elements from this collection that are contained in the other collection; all the others are removed. Once again, as it is the case for contains() or remove(), the other collection can be defined on any type.

remove has wrong link as above if the json file fixed then this one will be


thanks again and have a nice day :)

**Comment by Just-some-one** [comment]
indeed and thanks for you :)
