### ISSUE TITLE
Stream Api typo and confusing parts

### ISSUE THREAD

**Issue by Just-some-one** [java/devjava-content#117]
hello

for [map-filter-reduce](https://dev.java/learn/api/streams/map-filter-reduce/#terminal-operations)

this statement is confusing

> You cannot call more than one intermediate or terminal method on a stream. If you do so, you will get an IllegalStateException with the following message: "stream has already been operated upon or closed".

 
it sound like you can use single intermediate method or single terminal method and does not show how someone would faulty try to process the stream data more than once 

for [reducing](https://dev.java/learn/api/streams/reducing/)

> A stream can only have one intermediate or terminal operation call. You cannot reuse a stream; if you try to do that, you will get an IllegalStateException. 

stream can have more than one intermediate operation	

for [terminal-operations](https://dev.java/learn/api/streams/terminal-operations/#counting)

> The count() method is present in all the stream interfaces: both in specialized streams and streams of objects. It just returns the number of elements processed by that stream, in a long. This number can be huge, in fact greater than Integer.MAX_VALUE, because it is a long.

it does not explain from where that Integer.MAX_VALUE limit come from so maybe a breif of explanation about that array and all container of the collection framework like list (unless i miss something) limit  is Integer.MAX_VALUE

for [terminal-operations/foreach](https://dev.java/learn/api/streams/terminal-operations/#foreach)

```
Stream<String> strings = Stream.of("one", "two", "three", "four");

List<String> result = 
    strings.filter(s -> s.length() == 3)
           .map(String::toUpperCase)
           .collect(Collectors.toList());
```

> This collector creates an instance of ArrayList and adds the elements processed by your stream in it. So this pattern is not creating any side effect so there is no performance hit.

the collector create List but it not guarantee to which type it will return

> This pattern produces a special instance of List that is immutable. If what you need is a mutable list, you should stick to the first collector pattern. It also performs better than collecting your stream in an instance of ArrayList. This point is covered in the next paragraph. 

"If what you need is a mutable list, you should stick to the first collector pattern" the api mentioned it not guarantee to what characteristic (mutability, serializability, or thread-safety) of the returned List

for [terminal-operations/collecting-in-a-plain-arraylist](https://dev.java/learn/api/streams/terminal-operations/#collecting-in-a-plain-arraylist)

```
Stream<String> strings = Stream.of("one", "two", "three", "four");

List<String> result = 
    strings.filter(s -> s.length() == 3)
           .map(String::toUpperCase)
           .collect(Collectors.toList());

```

again for that code there no guarantee to what implementation of list is returned so this code and the paragraph related to it need to be changed

for [using-collectors](https://dev.java/learn/api/streams/using-collectors/#joining)

> This collector is very handy when you need to produce this kind of string of characters. You may be tempted to use it even if your data is not in a collection in the first place or with only a few elements. If this is the case, maybe using the String.join() factory class, or a StringJoiner object will work all the same, without paying the overhead of creating a stream. 

wrong link to String.join() method

for [using-collectors/toMap](https://dev.java/learn/api/streams/using-collectors/#toMap)

```
List<User> users = ...;

Map<Long, User> userCache = 
    users.stream()
         .collect(User::getPrimaryKey, 
                 Function.idendity());

```

it should be

```
List<User> users = ...;

        Map<Long, User> userCache =
                users.stream()
                        .collect(Collectors.toMap( User::getPrimaryKey,
                                Function.identity()));
```
                                
missing Collectors.toMap and typo on identity() method name

thanks for your time and have a nice day :)

**Comment by JosePaumard** [comment]
Done, thank you!

**Comment by Just-some-one** [comment]
thanks for you 


for [terminal-operations/foreach](https://dev.java/learn/api/streams/terminal-operations/#foreach)

Stream<String> strings = Stream.of("one", "two", "three", "four");

List<String> result = 
    strings.filter(s -> s.length() == 3)
           .map(String::toUpperCase)
           .collect(Collectors.toList());

>This collector creates an instance of ArrayList and adds the elements processed by your stream in it. So this pattern is not creating any side effect so there is no performance hit.

the collector create List but it not guarantee to which type it will return https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/util/stream/Collectors.html#toList()

>This pattern produces a special instance of [List](https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/util/List.html) that is unmodifiable. If what you need is a modifiable list, you should stick to the first collector pattern. It also may perform better than collecting your stream in an instance of ArrayList. This point is covered in the next paragraph.

"If what you need is a mutable list, you should stick to the first collector pattern" should remove that as first pattern does not guarantee that as in the api  https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/util/stream/Stream.html#toList()

for [terminal-operations/collecting-in-a-plain-arraylist](https://dev.java/learn/api/streams/terminal-operations/#collecting-in-a-plain-arraylist)

```
Stream<String> strings = Stream.of("one", "two", "three", "four");

List<String> result = 
    strings.filter(s -> s.length() == 3)
           .map(String::toUpperCase)
           .collect(Collectors.toList());
```

again for that code there no guarantee to what implementation of list is returned so this code and the paragraph related to it need to be changed

for [using-collectors/toMap](https://dev.java/learn/api/streams/using-collectors/#toMap)
```
List<User> users = ...;

Map<Long, User> userCache = 
    users.stream()
         .collect(User::getPrimaryKey, 
                 Function.idendity());
```
it should be

```
List<User> users = ...;

        Map<Long, User> userCache =
                users.stream()
                        .collect(Collectors.toMap( User::getPrimaryKey,
                                Function.identity()));
```
missing Collectors.toMap and typo on identity() method name

thanks for your time and have a nice day :)

**Comment by JosePaumard** [comment]
Done, thank you. 
I understand your concern about Collectors.toList() using an ArrayList. It's not in the spec, but this is the current implementation. The fact that it is currently a modifiable list would make the change to an unmodifiable implementation would be a breaking change, so it cant be done. And the way ArrayList.add() works makes it so that Stream.toList() may perform better in the case of the SIZED stream.

**Comment by Just-some-one** [comment]
thanks for you
and thanks for the explanation :)
