### ISSUE TITLE
Duplicate Bullet Point in "Creating Primitive Type Variables in Your Programs" Tutorial

### ISSUE THREAD

**Issue by VidyasagarYadav499** [java/devjava-content#123]
There is an unnecessary duplicate bullet point in the `long` data type description within the `Primitive Types` section.

### Problem:
The description of the `long` data type begins with a bullet point, but a second bullet point starts the next paragraph, even though both paragraphs are discussing the same topic (the `long` data type).

### Probable Solution:
There should only be a single bullet point that encompasses both paragraphs.

### Location:
[Primitive Types](https://dev.java/learn/language-basics/primitive-types/) page, where the bullet point for `long` data type starts.

### Screenshot:
![Screenshot 2024-08-25 105619](https://github.com/user-attachments/assets/5f44930a-b22e-4d77-9574-d6cd9c1e9eb5)

**Comment by JosePaumard** [comment]
Thank you for your report. I just published a small reorganization of the page to fix the issue.

**Comment by VidyasagarYadav499** [comment]
Glad to be of some help! Thank you for the quick fix!
