### ISSUE TITLE
New HTTP Client API Section

### ISSUE THREAD

**Issue by GrimReaper3223** [java/devjava-content#127]
### Website Section

Learn --> Mastering the API

### Proposal Details

Hello, how are you? I would like to propose that a section whose topic could be "The New HTTP Client API" be added. I think this would be very important to teach us about networking. It would also be interesting to teach us about how two different applications connect and I believe this could open doors for us to Servlets using Java EE (Of course, for those who wanted to go further in Servlets and look for tutorials on Java EE)

**Comment by danthe1st** [comment]
I think this may be a duplicate of #8 or #74.

**Comment by GrimReaper3223** [comment]
oh, okay. I will close this issue
