### ISSUE TITLE
Typo in  page  "Using the Var Type Identifier" of the "Java Language Basics" tutorial 

### ISSUE THREAD

**Issue by gloucklegnou** [java/devjava-content#130]
in [Using the Var Type Identifier](https://dev.java/learn/language-basics/using-var/) page, under [Restrictions on Using Var](https://dev.java/learn/language-basics/using-var/#restrictions) there is an error in the text (wrong variable name).

```
In that case, the compiler cannot guess the real type of message because is lacks an initializer.
```

should be

```
In that case, the compiler cannot guess the real type of greetings because is lacks an initializer.
```

**Comment by JosePaumard** [comment]
Thank you for your report. I just fixed the typo, and added some clarifications.
