### ISSUE TITLE
Modern I/O

### ISSUE THREAD

**Issue by carimura** [java/devjava-content#26]
### Approved Content Discussed in https://github.com/java/devjava-content/discussions/22

<div type='discussions-op-text'>

<sup>Originally posted by **cayhorstmann** June  7, 2023</sup>
### Content Details

An article on the more or less recent changes in I/O libraries, showing readers to use modern one-liners instead of loops with `BufferedReader`. An expanded version of https://horstmann.com/unblog/2023-04-09/index.html

### Website Section

Learn -> Tutorials -> Staying Aware of New Features?</div>

**Comment by carimura** [comment]
hi @cayhorstmann -- was this ever worked on? Just doing some cleaning up of issues. Thanks!

**Comment by cayhorstmann** [comment]
#66
