### ISSUE TITLE
Content license

### ISSUE THREAD

**Issue by danthe1st** [java/devjava-content#39]
The purpose of this repository is to provide Java-related content for everyone and allow that knowledge to be used.

However, I don't see a `LICENSE` file in this repository.
How is the existing content of this repository licensed?
And what about third-party/Community contributions? How do they know which license they provide their content under?
Does contributing require signing the OCA? If so, which one (or which projects) is required for this repository?

I think it might be important to sort this out before the first actual (content) contributions.

**Comment by carimura** [comment]
Thanks we'll make this clearer. All contributed content is made available under the UPL license. See examples here: https://dev.java/authors/

Contributing does require an OCA. There should be a project for Dev.java but I'll need to verify that.
