### ISSUE TITLE
[Request] enums

### ISSUE THREAD

**Issue by danthe1st** [java/devjava-content#40]
The [Classes and Objects section](https://dev.java/learn/classes-objects/) mentions covering enumerations. However, that part is missing.

I think a page about enumerations should be added there:
- What are enumerations?
- How to create them?
- What functionality do enumerations provide in Java?

**Comment by carimura** [comment]
Ya it does seem like we're missing a page on enums, thanks. Would you like to contribute something?

**Comment by danthe1st** [comment]
Yeah, I would like to add that.

**Comment by danthe1st** [comment]
Do I need to wait for this issue to get the [request] label in order to create a proposal issue?

**Comment by carimura** [comment]
Just approved this issue. You can assign it to yourself and start work!

**Comment by danthe1st** [comment]
> Just approved this issue. You can assign it to yourself and start work!

I think only maintainers/collaborators can assign issues.
If I am assigned, do I still need to create a Proposal issue?

**Comment by danthe1st** [comment]
In the meantime, this is my current draft (content-only): https://gist.github.com/danthe1st/b7ff869ee179ffbcf7e5bc9c1ca63c3d

**Comment by danthe1st** [comment]
Also, is it possible that the `Classes and Objects` section is missing in that repository?

**Comment by carimura** [comment]
@danthe1st good. Few small comments but I think we can do this as a PR. Are you able to get the app running and create the article as a PR? We can help here too if needed.

**Comment by danthe1st** [comment]
Yes, I got it running locally and created #45.
The issue I had is that the `Classes and Objects` section from dev.java isn't present in the version from this repository.

**Comment by carimura** [comment]
ah you're ahead of me, just saw the PR. Ok will take a look later today!

**Comment by danthe1st** [comment]
It's available now: https://dev.java/learn/classes-objects/enums/
