### ISSUE TITLE
[Request] Key Encapsulation Mechanism API

### ISSUE THREAD

**Issue by danthe1st** [java/devjava-content#42]
dev.java provides a section [Fundamentals of Security using JDK Libraries](https://dev.java/learn/security/).

Since the [Key Encapsulation Mechanism API](https://openjdk.org/jeps/452) has been added in Java 21, it could be useful to add an article for that.

**Comment by carimura** [comment]
Makes sense although I think there's other stuff that might take priority...  cc @ammbra who was working on some articles here.

**Comment by carimura** [comment]
sounds like this is being worked on already, thanks for suggestion @danthe1st !
