### ISSUE TITLE
[Request] Regexes

### ISSUE THREAD

**Issue by danthe1st** [java/devjava-content#48]
I think dev.java should contain an article on regexes.

Specifically, I would suggest that such an article includes:
- What are regexes?
- How can regexes be used in Java?
  - using `String` methods (`matches`/`replaceAll`/`split`)
  - Compiling `Pattern`s
  - using `Matcher` for finding occurences in `String`s, working with groups, etc.
- quick overview on regex features

**Comment by Just-some-one** [comment]
Hello @danthe1st 

there already [tutorial for that](https://dev.java/learn/regex/)

but i guess it would be nice to add extra lecture about the performance impact
