### ISSUE TITLE
Getting started with Java in IntelliJ

### ISSUE THREAD

**Issue by ammbra** [java/devjava-content#62]
### Website Section

Learn --> Tutorials --> Your First Java App.

### Proposal Details

Would be great to have a getting started with Java article and IntelliJ.

### Author References

Marit van Dijk (@mlvandijk) would be great to complete this ask 😸

**Comment by mlvandijk** [comment]
Hi Ana-Maria,

Before I start writing, I suggest the following title & outline. 

Suggested title: Building a Java application with IntelliJ IDEA

Suggested outline:

- Introduction (IDEs in general, IntelliJ IDEA specifically)
- Installing IntelliJ IDEA
- Learning the IDE / most useful shortcuts (optional)
- Creating a project
- Project tool window (optional)
- Writing and editing code
- Running your application
- Testing and debugging
- Refactoring code
- Documenting code
- Evolving the project (optional)

Note: (optional) means I'm not 100% sure yet whether these will be included in the final version.

Please let me know what you think and whether to go ahead. Thank you!

**Comment by ammbra** [comment]
Hey Marit,

Thank you for your outline. I like it and for the moment would say to keep it like this:

- Introduction 
- Installing IntelliJ IDEA
- Creating a project
- Writing and editing code
- Running your application
- Testing and debugging
- Refactoring code
- Documenting code
- Evolving the project (could be the ending part)

Maybe the intro and the installation part can be combined, but we will see that together once the first draft is ready.

Good luck 😉

**Comment by mlvandijk** [comment]
Thanks Ana-Maria, 
I'll get started on that and keep you posted.

**Comment by dbc2201** [comment]
Hi @mlvandijk,

I've been teaching Java using IntelliJ IDEA for the last 6 years, and would love to help out on this. Where do I start? 😄

**Comment by danthe1st** [comment]
Would it make sense to create a group of articles for IDEs (since there's already an article for the Java Platform Plugin in VSC)?
After all, if there's an article for VSC and one for IntelliJ, I think there should be one for Eclipse as well.

**Comment by mlvandijk** [comment]
Hi @ammbra - I should have a draft for you soon. 
Would it be ok to split Testing and Debugging into 2 sections? (otherwise the section will be quite long compared to the other sections)
And I'm thinking of adding a short section on vcs (git) support, and on searching & navigating (another upside of using an IDE). Would that be ok?
Thanks!

**Comment by ammbra** [comment]
Hey Marit,

Regarding splitting a section: please consider to do as you see fit for the article and will decide afterwards if for any reason it should be more compact. As for the vcs support: the article should be a getting started with Java in IntelliJ and ,in my opinion, adding vcs would be too much for a beginner.

Looking forward to reading your draft! 

Warm regards,
Ana
