### ISSUE TITLE
Addition of some important things in Dev.java

### ISSUE THREAD

**Issue by GrimReaper3223** [java/devjava-content#64]
Hello everybody! I hope you are well.

I would like to give an idea to everyone who maintains Dev.java.
I'm learning a lot there ❤️ I've already completed several topics and this makes me very excited and motivated to always want more. But I've been noticing something for a while: I noticed that there are no tutorials on networks (http) and on Databases (Maybe it's me who's not finding it, even though I've already viewed everything and haven't found it).

Could you add tutorials related to this? It would also be interesting, in addition to the already added JavaFX tutorial, Also have a tutorial related to swing? It would be interesting, since swing is easier to learn than JavaFX. Swing would be like a prelude to JavaFX.

It would also be helpful if the tutorial related to threads and concurrency were added to Dev.java.

I know that all this already exists in the documentation tutorial, but it would be nice if it were more exemplified in the dev.java website.

In advance, I am immensely grateful and, thank you very much for this great chance to learn and get to know this perfect tool that is Java ❤️❤️🥹

**Comment by carimura** [comment]
thank you for the suggestions! Some of these things have been added, others will be in the future, and some might not fit. But keep an eye out for new content, and hopefully ways to subscribe to new content.
