### ISSUE TITLE
[Request] Writing Java applications with Eclipse

### ISSUE THREAD

**Issue by danthe1st** [java/devjava-content#68]
Since it seems that we already have an article about using Java in VSC and at an article about IntelliJ is in the process of being added in #62, I think another article should be added for the Eclipse IDE.

There are many people using it so it would be weird to leave it out.

### Website section
Learn > Tutorials > Your First Java App

### Details
I could imagine the following sections:
- Introduction/installation
- creating Java projects
  - possibly including build tools (I am not talking about an introduction to build tools, just about creating Maven/Gradle projects in Eclipse)
- Debugging functionality (Debug perspective, associated buttons, etc)
- Content assist
  - I don't think it's necessary to talk about setting auto activation keys but this is a possibility as well.
- Differentiation between workspaces and projects
- possibly Ctrl+1 (quick fix), Ctrl+3 (quick access)
- Refactoring/Generation/Autoformatting
  - only a quick overview showing the options being there
  - not including any configuration of autoformatting etc

### Author references
I would be interested in writing this but I am also open to other people writing it.

**Comment by danthe1st** [comment]
If we have multiple articles for IDEs, it might be a good idea to add a category similar to `Working with IDEs`.

**Comment by tfroment** [comment]
Hi @danthe1st,
As a newcomer in the role of Eclipse IDE Program Manager, I'm joining the ongoing discussion. Personally, I find several of these topics very interesting for an article. I will share about them at the next Steering Committee meeting of the WG, scheduled for next Tuesday, and I'll get back to you promptly....

**Comment by danthe1st** [comment]
@tfroment If there are preferences for who writes the article within the Eclipse Foundation/Eclipse IDE Working Group/Steering Comittee, I have no objections about these people writing that article. They are likely way more qualified than I am.

That being said, this article request doesn't yet have the `approved` label.
@ammbra Since you seem to be in the discussion of the corresponding IntelliJ IDEA article, are you ok with a corresponding article for the Eclipse IDE being written?

**Comment by mpalat** [comment]
@danthe1st  - There was an ask for me taking up this activity in today's meeting from Eclipde IDE WG. @tfroment was there in this meeting. Am very happy to take this up.

**Comment by danthe1st** [comment]
I have no objections regarding that. However, I want to note that this article is still not approved from Oracle's side.

**Comment by noopur2507** [comment]
@danthe1st @mpalat As discussed with both of you, I would be glad to co-author this article.

**Comment by ammbra** [comment]
Hi @danthe1st,

Thank you for raising this issue. We looked over your initial suggestion and think that it would be good to have such an article, having an exclusive focus on a beginner's perspective when starting with Java and Eclipse IDE. The structure you proposed sounds reasonable from a beginner's point of view, just have in mind a few things when you are writing it:
* align it as a logical complimentary article for the 'getting started with Java and IDE series' (intellij, vscode articles)
* avoid providing information that overwhelms a beginner with Java (details on build tools, versioning, 3rd party libraries, information related to the JDK, etc.).
* if you provide key combinations for certain IDE functionalities, those should be given for Windows/Linux/MacOS.
* as IDEs continue to improve and thus add/change some of their features, the content of this article will require your periodical review and update.
As you are already a contributor to dev.java, we think that you should be the lead author of this article. In case other folks would like to help you, including providing feedback on your written piece, they should also sign the OCA.

**Comment by danthe1st** [comment]
I have now written a first draft of my article in #77.
While it isn't finished, I welcome anyone who cares to take a look at it. @noopur2507 @mpalat
However, please note that @ammbra mentioned in the above comment:
- If you want to contribute content, make sure you have signed the OCA.
  - For example if I forgot a section that is fairly important for beginners (e.g. interactive tutorials) or someone wants to write about Perspectives/Views
  - In such a situation, please write a comment under the PR saying you wanted to write it to avoid unnecessary work/two people writing the same thing)
- This shouldn't have information that isn't necessary for beginners.

It would be great if someone could verify the key combinations for MacOS.
