### ISSUE TITLE
Effectively broken link in README.md

### ISSUE THREAD

**Issue by jaakristioja** [java/devjava-content#73]
The README.md file refers to the root web page of inside.java in a manner suggesting that the target contains an announcement on accepting contributions to dev.java:

https://github.com/java/devjava-content/blob/50826e963ff22a11569a0218dca048314e1db7ba/README.md?plain=1#L5

I wasted at least 15 minutes trying to find the respective announcement on the target website but was unable to find it. I'd say that this link is effectively broken. The inside.java web page contains many news items, and if the respective announcement is contained in one of these many, the link in README.md should refer to that news item instead of the root page.

**Comment by jaakristioja** [comment]
Also, when exactly is "recently"?

**Comment by carimura** [comment]
Fair enough, thank you for spotting this. Fixed.
