### ISSUE TITLE
"References for the latest release" pointing to 21

### ISSUE THREAD

**Issue by danthe1st** [java/devjava-content#75]
On [/learn](https://dev.java/learn/), the section `References for the latest release` contains multiple links to sites about JDK 21 even though the latest release is 22:
- Java Documentation 
- Java API Docs
- Java Release Notes

I propose to either update these links to 22 or change the heading to not say "latest release".

**Comment by SimonVerhoeven** [comment]
And the footer:
![image](https://github.com/java/devjava-content/assets/5849845/dd7ae629-73fe-48b0-b5dc-6d129ebfe802)

**Comment by wkorando** [comment]
Updated the footer to reference JDK 22.
