### ISSUE TITLE
[ Typo ] in Using Operators in your programs

### ISSUE THREAD

**Issue by JoyelJohny** [java/devjava-content#81]
There is a typo error in [Home](https://dev.java/) > [Tutorials](https://dev.java/learn) >[ Java Language Basics ](https://dev.java/learn/language-basics/)> Using Operators in Your Programs

Under Bitwise and Bit Shift Operators Section it is written Bitwise | as Bitwise &

![image](https://github.com/java/devjava-content/assets/81413791/eaa0d907-af9a-421c-b39e-d6c8579980b3)

**Comment by JosePaumard** [comment]
Thank you for your report. This typo is now fixed.
