### ISSUE TITLE
Common Problems (and their solutions) pointing to wrong anchor

### ISSUE THREAD

**Issue by danthe1st** [java/devjava-content#82]
The [FAQs on dev.java](https://dev.java/learn/faq/) contain a link `Common Problems (and their solutions)` which links to https://dev.java/learn/getting-started/#anchor_9.
However, `#anchor_9` is not available on that page. It should instead link to [`#common-problems`](https://dev.java/learn/getting-started/#common-problems).

The link is specified [here](https://github.com/java/devjava-content/blob/50826e963ff22a11569a0218dca048314e1db7ba/app/pages/learn/03_faq/index.md?plain=1#L15)

**Comment by carimura** [comment]
thanks, fixed in a different repo!
