### ISSUE TITLE
Typo in exceptions description

### ISSUE THREAD

**Issue by danthe1st** [java/devjava-content#86]
In the section Getting to Know the Language on https://dev.java/learn/, the description of the `Exceptions` article series is as follows:
> Using exceptions to handle errors and other exceptionnal events.

I think it should be `exceptional` instead of `exceptionnal`.
In [the description on the series page](https://dev.java/learn/exceptions/), this is stated correctly.

**Comment by Just-some-one** [comment]
this one is fixed
