### ISSUE TITLE
Misleading variable name

### ISSUE THREAD

**Issue by jaakristioja** [java/devjava-content#89]
The [Using Lambdas Expressions in Your Application](https://dev.java/learn/lambdas/functional-interfaces/) page the first code excerpt under the [Passing a Predicate to a Collection](https://dev.java/learn/lambdas/functional-interfaces/#passing-a-predicate-to-a-collection) heading contains a misleading variable name:

```java
Predicate<String> isOddLength = s -> s.length() % 2 == 0;
```

I suggest this variable be renamed to `isEvenLength` instead.

**Comment by JosePaumard** [comment]
Thank you for your comment. Indeed `isEvenLength` makes more sense. I just changed the variable name.
