### ISSUE TITLE
Incorrect variable type and name

### ISSUE THREAD

**Issue by jaakristioja** [java/devjava-content#91]
Under [Methods That Do Not Take Any Argument](https://dev.java/learn/lambdas/method-references/#methods-that-do-not-take-any-argument) the following example

```java
Function<String, Integer> toLength = User::getName;
```

seems to erronously contain some copy-paste from some previous code excerpt and should instead read something like

```java
Function<User, String> getName = User::getName;
```

i.e. with both the type and name of the variable changed.

**Comment by JosePaumard** [comment]
Fixed. Thank you again for your reports!
