### ISSUE TITLE
Missing ! character in example code

### ISSUE THREAD

**Issue by jaakristioja** [java/devjava-content#92]
Under [Chaining Predicates with Default Methods](https://dev.java/learn/lambdas/combining-chaining-composing/#chaining-predicates) in the second code excerpt the line

```java
Predicate<String> nonEmpty = s -> s.isEmpty();
```

Is missing a `!` character and should instead read

```java
Predicate<String> nonEmpty = s -> !s.isEmpty();
```

**Comment by JosePaumard** [comment]
Fixed, thank you for your report.
