### ISSUE TITLE
Misleading consumer name

### ISSUE THREAD

**Issue by jaakristioja** [java/devjava-content#93]
Under [Chaining Consumers with Default Methods](https://dev.java/learn/lambdas/combining-chaining-composing/#chaining-predicates) the variable `printAndLog` is defined as follows:

```java
Consumer<String> printAndLog = log.andThen(print);
```

I suggest the variable be renamed to `logAndPrint` as the semantics of the resulting consumer are are to first log and then print, not the other way around.

**Comment by JosePaumard** [comment]
Fixed, thank you for your report.
