### ISSUE TITLE
bug on code for controlling-flow tutorial

### ISSUE THREAD

**Issue by Just-some-one** [java/devjava-content#99]
Hello

for the following [language-basics/controlling-flow](https://dev.java/learn/language-basics/controlling-flow/#yield) which i can not see here on the https://github.com/java/devjava-content/tree/main/app/pages/learn/01_tutorial/03_getting-to-know-the-language/02_basics

the example code

```
class Test {
    enum Day {
        MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY
    }

    public String calculate(Day d) {
        return switch (d) {
            case SATURDAY, SUNDAY -> "week-end";
                default -> {
                    int remainingWorkDays = 5 - d.ordinal();
                    yield remainingWorkDays;
                }
            };
    }
}
```

would not compile as the return type is string but remainingWorkDays is integer
so the proposed suggestion is

```
class Test {
    enum Day {
        MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY
    }

    public String calculate(Day d) {
        return switch (d) {
            case SATURDAY, SUNDAY -> "week-end";
                default -> {
                    int remainingWorkDays = 5 - d.ordinal();
                    yield String.valueOf(remainingWorkDays);
                }
            };
    }
}
```

glad to see the content on github so it easy for everyone to participate and fix issue and have a nice day :)

**Comment by danthe1st** [comment]
I think the return type is now `int` on the site which still doesn't work because of the `String` `"week-end"`.

**Comment by JosePaumard** [comment]
Done, thank you.

**Comment by Just-some-one** [comment]
> I think the return type is now `int` on the site which still doesn't work because of the `String` `"week-end"`.

you are correct looks like i copy from my modified code 
thanks

**Comment by Just-some-one** [comment]
> Done, thank you.

thank you
